# Servidor B - Configuración P2P
# Basado en src/main/resources/config.properties

jdbc.url=jdbc:mysql://localhost:3306/chat_universitario
jdbc.username=root
jdbc.password=0000
jdbc.driver=com.mysql.cj.jdbc.Driver

jdbc.pool.min=1
jdbc.pool.max=2

server.port=5003
server.host=0.0.0.0
server.id=chat-server-b
server.p2p.port=5200
server.peers=127.0.0.1:5100,127.0.0.1:5300,127.0.0.1:5400
server.max.usuarios.conectados=100

log.nivel=INFO
log.archivo=logs/servidor-b.log

archivos.ruta.base=archivos/servidor-b
archivos.audio.max.size.mb=10
